### ISSUE TITLE
Only powers of 3 work in parent_grid_ratio of nests

### ISSUE THREAD

**Issue by sfalmo** [JiriRichter/WRFDomainWizard#2]
After defining the MOAD and adding a nest, a default parent_grid_ratio of 3 is selected. One cannot change this ratio to other numbers than 1, 3 or 9 without e_we and e_sn failing to validate.
When changing parent_grid_ratio, valid numbers for e_we and e_sn are not recalculated. Instead, the old ones are kept. But then, the stepsize of the e_we and e_sn selector is set to parent_grid_ratio, making it impossible to select a number that both fulfills
`e = k * parent_grid_ratio + e_old`
and
`e = n * parent_grid_ratio + 1`
for any `k, n`.
A simple fix would be a change event listener on parent_grid_ratio that recalculates appropriate "starting values" for e_we and e_sn, analogous to [leaflet.wrf-grid.js#L862-L856](https://github.com/JiriRichter/WRFDomainWizard/blob/1558d482f99e6569eb431ea059a116d9210fa08b/js/leaflet.wrf-grid.js#L862-L865)

**Comment by HathewayWill** [comment]
can confrim it doesn't allow mixed ratios either

for example 1 5 3

**Comment by HathewayWill** [comment]
![image](https://github.com/JiriRichter/WRFDomainWizard/assets/118180342/eb155fdc-15e6-40c0-b9d2-8685bd62cda3)
[namelist.zip](https://github.com/JiriRichter/WRFDomainWizard/files/13759166/namelist.zip)

**Comment by JiriRichter** [comment]
@sfalmo , @HathewayWill ,
thank you for reporting the issue. I have not worked on this project in year and honestly was not aware people are using it. I'll have a look at the problem.

**Comment by HathewayWill** [comment]
@JiriRichter 

NCAR deleted the domain wizard and your site has been taking off on the forums
