### ISSUE TITLE
dx & dy for grid should always be equal

### ISSUE THREAD

**Issue by HathewayWill** [JiriRichter/WRFDomainWizard#21]
**Describe the bug**
Dx and Dy grid size can only be eqaul to each other.

for example

dx=9000
dy=9000 
is okay

but 

dx=9000
dy=8000
is not okay

![image](https://github.com/JiriRichter/WRFDomainWizard/assets/118180342/3741bf5d-8b51-496e-b79f-db47a32fadde)

**Comment by JiriRichter** [comment]
@HathewayWill , according to https://www2.mmm.ucar.edu/wrf/users/namelist_best_prac_wps.html it seems same values are only recommended for Mercator, Polar, and Lambert projections. It sounds like in general it should be possible to set different values. I guess, in practice, this almost never happens.

**Comment by HathewayWill** [comment]
@JiriRichter 

I have never seen it done at different grid lengths, but I guess it can stay the same.

Different grid lengths would be rectangles and wrf likes squares.

I'll clarify with ncar

**Comment by HathewayWill** [comment]
https://forum.mmm.ucar.edu/threads/when-would-dx-and-dy-not-be-equal.19635/#post-47562

**Comment by JiriRichter** [comment]
Thanks for chasing down clarification on this. I removed the question label and will mark this as a feature request

**Comment by HathewayWill** [comment]
@JiriRichter sounds good

**Comment by JiriRichter** [comment]
@HathewayWill , can you please have a look at https://jiririchter.github.io/WRFDomainWizard/. I disabled setting DY by default. This can be optionally changed in the settings. If everything looks good. Please, close this issue as resolved

**Comment by HathewayWill** [comment]
![Screenshot from 2024-11-17 07-18-14](https://github.com/user-attachments/assets/a7df0bf8-cf8b-4884-a908-7e61ab94081f)
![Screenshot from 2024-11-17 07-18-02](https://github.com/user-attachments/assets/1937aec6-5936-461c-87e1-c7cacdb795aa)
![Screenshot from 2024-11-17 07-17-41](https://github.com/user-attachments/assets/7e8d2486-168e-48b5-a6a3-3e2da771d944)
![Screenshot from 2024-11-17 07-17-29](https://github.com/user-attachments/assets/d8fa990a-4399-4f96-8a6f-a0f5156d12c3)


Lat Long should have the option to be adjusted dx and dy individually as that is how it works.

The other 3 are not adjusting with the dx.  Dy is stuck on 12km

**Comment by JiriRichter** [comment]
That's not good. I'll fix it later today.

**Comment by HathewayWill** [comment]
![Screenshot from 2024-11-17 18-08-56](https://github.com/user-attachments/assets/fa2b4e94-c506-495c-995b-9c36c5c7e93c)
![Screenshot from 2024-11-17 18-08-45](https://github.com/user-attachments/assets/a1240f40-0bcb-4417-bc73-60f8969f5df6)
![Screenshot from 2024-11-17 18-07-56](https://github.com/user-attachments/assets/1c8919cf-f46a-4034-8b39-035a953e290f)


Reopening this, default values are 8000 and 12000.  If you press enter the 12000  value will not change to 8000.  But if you enter any other number then it will change.

Other then that it works as expected

**Comment by JiriRichter** [comment]
I found the problem
