### ISSUE TITLE
Misspelled wrf_core value ARW

### ISSUE THREAD

**Issue by JiriRichter** [JiriRichter/WRFDomainWizard#23]
There are three spelling mistakes, for example:
in file [src/js/utils/namelist.wps.js](https://github.com/JiriRichter/WRFDomainWizard/blob/8fadd7b1219e1c24fb3df9c3552231034b2ac8a0/src/js/utils/namelist.wps.js#L133)
this.share.wrf_core = 'AWR';
this.share.wrf_core = 'ARW' may be right.

_Originally posted by @andrewsoong in https://github.com/JiriRichter/WRFDomainWizard/issues/12#issuecomment-2042007915_

**Comment by andrewsoong** [comment]
And https://github.com/JiriRichter/WRFDomainWizard/blob/8fadd7b1219e1c24fb3df9c3552231034b2ac8a0/index.html#L82
https://github.com/JiriRichter/WRFDomainWizard/blob/8fadd7b1219e1c24fb3df9c3552231034b2ac8a0/build/index.html#L82
[src/index.html](https://github.com/JiriRichter/WRFDomainWizard/blob/8fadd7b1219e1c24fb3df9c3552231034b2ac8a0/src/index.html#L82)
