### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of null (reading 'opt_ignore_dom_center') @ https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:1095

### ISSUE THREAD

**Issue by turbulentlens** [JiriRichter/WRFDomainWizard#35]
Error: Uncaught TypeError: Cannot read properties of null (reading 'opt_ignore_dom_center')
Timestamp: 2024-07-25T22:31:21.467Z
Source: https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js
Line: 1095
Stack:
TypeError: Cannot read properties of null (reading 'opt_ignore_dom_center')
    at new Namelist (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:1095:28)
    at new WPSNamelist (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:1631:14)
    at reader.onload (https://jiririchter.github.io/WRFDomainWizard/build/js/wrf-domain-wizard.js:13880:27)

**Comment by JiriRichter** [comment]
I was able to reproduce the issue by placing the 'opt_ignore_dom_center' property outside of a namelist section. This is not valid but the tool should be able to handle this gracefuly by either ignoring such vartiables of displaying appropriate error.

&share
 wrf_core             = 'ARW'
 max_dom              = 1
 start_date           = '2024-07-04_03:00:00'
 end_date             = '2024-07-04_18:00:00'
 interval_seconds     = 21600
 io_form_geogrid      = 2
 debug_level          = 0
/

&geogrid
 parent_id            = 1
 parent_grid_ratio    = 1
 i_parent_start       = 1
 j_parent_start       = 1
 e_we                 = 68
 e_sn                 = 60
 geog_data_res        = 'default'
 dx                   = 12000
 dy                   = 12000
 map_proj             = 'lambert'
 ref_lat              = 46.169
 ref_lon              = -117.422
 truelat1             = 46.169
 truelat2             = 46.169
 pole_lat             = 90
 pole_lon             = 0
 stand_lon            = -117.422
 geog_data_path       = 'geog'
 opt_geogrid_tbl_path = './geogrid/'
/

&ungrib
 out_format           = 'WPS'
 prefix               = 'FILE'
/

&metgrid
 fg_name              = 'FILE'
 io_form_metgrid      = 2
 opt_metgrid_tbl_path = './metgrid'
/

opt_ignore_dom_center = .true.

**Comment by JiriRichter** [comment]
I improved error handling of invalid WPS namelist files. In the case above, it will show an error there is a variable outside of a group.
