### ISSUE TITLE
Error: TypeError: this._mainGrid.nests[0].projection is undefined @ https://wrfdomainwizard.net/js/wrf-domain-wizard.js:11578

### ISSUE THREAD

**Issue by kingo21** [JiriRichter/WRFDomainWizard#41]
Error: TypeError: this._mainGrid.nests[0].projection is undefined
Timestamp: 2024-08-18T15:48:33.770Z
Source: https://wrfdomainwizard.net/js/wrf-domain-wizard.js
Line: 11578
Stack:
WRFDomain.prototype.removeMainGrid@https://wrfdomainwizard.net/js/wrf-domain-wizard.js:11578:5
SidebarDomainsPanel/<@https://wrfdomainwizard.net/js/wrf-domain-wizard.js:11705:14
dispatch@https://wrfdomainwizard.net/lib/jquery.min.js:2:40035
add/v.handle@https://wrfdomainwizard.net/lib/jquery.min.js:2:38006

**Comment by JiriRichter** [comment]
Hi @kingo21, thank you for reporting this issue. Can you please provide more information about what actions you have taken before hitting this error?
