### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'unstaggered_ij_to_latlon') @ https://wrfdomainwizard.net/js/wrf-domain-wizard.js:27620

### ISSUE THREAD

**Issue by Koar-create** [JiriRichter/WRFDomainWizard#51]
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'unstaggered_ij_to_latlon')
Timestamp: 2024-10-18T17:53:18.049Z
Source: https://wrfdomainwizard.net/js/wrf-domain-wizard.js
Line: 27620
Stack:
TypeError: Cannot read properties of undefined (reading 'unstaggered_ij_to_latlon')
    at WRFDomain.addMainGrid (https://wrfdomainwizard.net/js/wrf-domain-wizard.js:27620:42)
    at HTMLButtonElement.<anonymous> (https://wrfdomainwizard.net/js/wrf-domain-wizard.js:27782:14)
    at HTMLButtonElement.dispatch (https://wrfdomainwizard.net/lib/jquery.min.js:2:40035)
    at v.handle (https://wrfdomainwizard.net/lib/jquery.min.js:2:38006)

**Comment by JiriRichter** [comment]
@Koar-create, thank you for reporting this issue. Would you be able to provide steps I can follow to reproduce this?

**Comment by Koar-create** [comment]
Yes, that error appears whenever I wanna add a parent domain for the current domain. By the way adding nested domains works normally. Let me know if you need further information.

**Comment by JiriRichter** [comment]
Thanks for the detail. I think this issue was reported by another person. I'll try to get it fixed this week.
