### ISSUE TITLE
Zoom stepping.

### ISSUE THREAD

**Issue by HathewayWill** [JiriRichter/WRFDomainWizard#57]
Sometimes when working with small domains the zoom (+/-) steps are too powerful.  Perhaps changing the (+/-) to a slider bar?

**Comment by JiriRichter** [comment]
The zoom control is provided by the mapping library [leaflet](https://leafletjs.com/) and the zoom levels are given by the map tile provider. This cannot be easily accomplished. I'm going to close this one.
