### ISSUE TITLE
Topography Layers not working

### ISSUE THREAD

**Issue by HathewayWill** [JiriRichter/WRFDomainWizard#6]
**Describe the bug**
When changing the map layers on the website some of them are blank.

**To Reproduce**
Click on Open Topo Map, Wikimania, Esri Delorne

Does not show 

**Expected behavior**
Should be able to quickly show and load maps

**Screenshots**

![Screenshot from 2024-01-29 22-18-15](https://github.com/JiriRichter/WRFDomainWizard/assets/118180342/e7c652d1-d7dd-453d-b4db-252ef68bf5c5)
![Screenshot from 2024-01-29 22-18-24](https://github.com/JiriRichter/WRFDomainWizard/assets/118180342/3eba2a83-c17b-43ff-b506-facf443fc51d)
![Screenshot from 2024-01-29 22-18-29](https://github.com/JiriRichter/WRFDomainWizard/assets/118180342/e62d444e-e333-43ae-bd50-29b69466d340)
![Screenshot from 2024-01-29 22-18-33](https://github.com/JiriRichter/WRFDomainWizard/assets/118180342/a93512ef-e082-4d9a-87b9-bd1b571fd964)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.
 - Browser Chrome
 - Version 121.0.6167.85 (Official Build) (64-bit)

**Additional context**
Minor issue but worth a look

**Comment by JiriRichter** [comment]
Thanks for reporting. This was resolved as part of migration to NPM dev environment and updating dependencies. The demo still points to the original code because of known code bugs in the new code base. All this should be resolved after the next merge.
